### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by CedX** [sindresorhus/is-root#1]
It would be very cool if the library could work on Windows, and return a meaningful value instead of `undefined`. I know that `process.getuid` function is not available on Windows, but I'm convinced that a workaround can be found.

**Comment by kevva** [comment]
There's really no real equivalent to the user `root` in Windows. You'd guess it'd be the user `Administrator` but then again, any user could have the same privileges. See http://en.wikipedia.org/wiki/Superuser#Microsoft_Windows.

**Comment by sindresorhus** [comment]
I'm happy to receive a pull request, but I'm pretty sure there's no good workaround.

**Comment by CedX** [comment]
No luck: I've searched a lot, but unfortunately I haven't found any solution (@kevva is right: the concept of user identifier, as used by the current implementation, doesn't exist on Windows).
We can't rely on the "Administrator" account as its name is localized (so it's "Administrateur" in French, "Administrador" in Spanish, and so on... a bit boring to implement!).
Sorry to have raised this issue before searching if it was possible.

**Comment by kevva** [comment]
No problem :).
