### ISSUE TITLE
is-root always returns false in Windows.

### ISSUE THREAD

**Issue by jviotti** [sindresorhus/is-root#2]
`process.getuid()` seems to be always `undefined` in Windows, therefore `isRoot()` always returns `false` in that platform.

Is there a way to check that the user is a Windows administrator and potentially integrate with `is-root`?

**Comment by jviotti** [comment]
Maybe we can reuse `isAdminUser()` from https://github.com/coreybutler/node-windows?

**Comment by arthurvr** [comment]
Duplicate of https://github.com/sindresorhus/is-root/issues/1. There's no root user on Windows. Checking if somebody is Admin is possible but it isn't really an equivalent of being root.
