### ISSUE TITLE
The package uploaded to npm is not licensed

### ISSUE THREAD

**Issue by honzajavorek** [sindresorhus/is-root#5]
The npm distribution of this package is not properly licensed. It does not contain full license text, which is an issue - see https://github.com/babel/babel/pull/7308#issuecomment-367615152

Effectively, this way the source code distributed on npm is unlicensed and cannot be used by anyone else (or, to be more precise, by anyone who cares about licensing).

- `license` field in `package.json`: MIT
- GitHub repository license file: license
- npm package contents license: (missing) :warning:

To reproduce this issue:

```shell
$ mkdir /tmp/foobar
$ cd /tmp/foobar
$ npm install is-root
$ ls -al ./node_modules/is-root/  # look for a license file
```

Related issue: https://github.com/sindresorhus/ama/issues/537

**Comment by sindresorhus** [comment]
Done
